title: BUI THANH DAT's Homepage
page-top-title: BUI THANH DAT
top-section-bg-text: Electronics & Telecommunications Engineering
home-subtitle: BUI THANH DAT
copyright-text: '&copy; BUI THANH DAT 2024-2025. All Rights Reserved.'
